name: GitHub Metrics
on:
  schedule: [{ cron: "0 * * * *" }]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories, metadata
          config_timezone: Asia/Kolkata
          plugin_languages: yes
          plugin_streak: yes
          plugin_achievements: yes
          plugin_notable: yes
          plugin_isocalendar: yes
