name: GitHub Metrics
on:
  schedule: [{ cron: "0 2 * * *" }] # Every day at 2:00 AM IST
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Token to access GitHub API (defined in repo secrets)
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
          base: header, repositories, metadata
          config_timezone: Asia/Kolkata

          # Plugins (customizable)
          plugin_languages: yes
          plugin_achievements: yes
          plugin_streak: yes
          plugin_isocalendar: yes
          plugin_notable: yes
